micronaut:
  application:
    name: gymTrendsAnalyzer
netty:
  default:
    allocator:
      max-order: 3
gym:
  username: ${GYM_USERNAME:}
  pin: ${GYM_PIN:}
  url:
    member: ${GYM_MEMBER_API_URL}
    api: ${GYM_API_URL}
    login: ${LOGIN_API_URL}

cron:
  hourly: 0 0/10 * * * ?

app:
  server:
    name: ${SERVER_NAME:localhost}
    port: ${SERVER_PORT:8080}
  service:
    url: http://${app.server.name}:${app.server.port}/
