micronaut:
  application:
    name: gymTrendsAnalyzer
netty:
  default:
    allocator:
      max-order: 3
gym:
  username: ${USERNAME}
  pin: ${PIN}
  url:
    member: ${GYM_MEMBER_API_URL:https://www.google.com}
    api: ${GYM_API_URL}
    login: ${LOGIN_URL}

cron:
  hourly: 0 0/10 * * * ?

app:
  server:
    name: ${SERVER_NAME:localhost}
    port: ${SERVER_PORT:8080}
  service:
    url: http://${app.server.name}:${app.server.port}/

file.path: ./file.csv
